---
proxy_hosts:
  - name: netbox
    domains:
      - netbox.klsll.com
    forward_host: 192.168.20.14
    forward_port: 8001
    scheme: http
    websocket: true
    certificate: klsll-wildcard
    ssl_forced: true
    hsts: true
    http2: true

dns_records:
  - name: netbox.klsll.com
    type: A
    value: 192.168.20.50
    ttl: 3600
