---
proxy_hosts:
  - name: paperless-ai
    domains:
      - paperless-ai.klsll.com
    forward_host: 192.168.20.14
    forward_port: 3090
    scheme: http
    websocket: true
    certificate: klsll-wildcard
    ssl_forced: true
    hsts: true
    http2: true

dns_records:
  - name: paperless-ai.klsll.com
    type: A
    value: 192.168.20.50
    ttl: 3600
