---
proxy_hosts:
  - name: reunion-api
    domains:
      - api.reunion.klsll.com
    forward_host: 192.168.20.14
    forward_port: 8094
    scheme: http
    websocket: true
    certificate: klsll-wildcard
    ssl_forced: true
    hsts: true
    http2: true

dns_records:
  - name: api.reunion.klsll.com
    type: A
    value: 192.168.20.50
    ttl: 3600
