---
cadvisor_version: "0.55.1"
cadvisor_image: "ghcr.io/google/cadvisor"
cadvisor_port: 8081
cadvisor_compose_dir: /opt/cadvisor
cadvisor_icon: >-
  https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cadvisor.png
