---
# Notion MCP Server defaults

# Container settings
notion_mcp_image: "notion-mcp-server:latest"
notion_mcp_container_name: "notion-mcp-public"
notion_mcp_port: 3000
notion_mcp_icon: >-
  https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/notion.png
notion_mcp_webui_url: >-
  http://{{ ansible_host }}:{{ notion_mcp_port }}/mcp

# MCP settings
notion_mcp_host: "0.0.0.0"
notion_mcp_transport: "streamable-http"

# Notion settings
notion_op_item: "Notion MCP Integration"
notion_token: >-
  {{ lookup('env', 'NOTION_TOKEN')
  | default(vars.get('notion_token_vault', ''), true)
  | default('', true) }}
auth_token: "notion-mcp-secret-2024"  # Custom auth token for HTTP transport

# Timezone
timezone: "America/Phoenix"
