---
all:
  children:
    unraid:
      hosts:
        unraid-server:
          ansible_host: 192.168.20.14
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab
          ansible_python_interpreter: /usr/bin/python3.11
    windows_gpu:
      hosts:
        spraycheese:
          ansible_host: 192.168.20.50
          ansible_user: james
          ansible_connection: ssh
    pve:
      hosts:
        pve-01:
          ansible_host: 192.168.20.100  # replace with the Proxmox host IP or hostname
          ansible_user: root
        pve-02:
          ansible_host: 192.168.20.101  # replace with the Proxmox host IP or hostname
          ansible_user: root
      vars:
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab
    edge_devices:
      hosts:
        jetson.lab:
          ansible_host: 192.168.20.169
          ansible_user: james
      vars:
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    tt:
      hosts:
        tt1:
          ansible_host: 192.168.20.2
          ansible_user: james
          ansible_python_interpreter: /usr/bin/python3.12
          ansible_become: true
          ansible_become_method: sudo
        tt2:
          ansible_host: 192.168.20.3
          ansible_user: james
          ansible_python_interpreter: /usr/bin/python3.12
          ansible_become: true
          ansible_become_method: sudo
      vars:
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab
    agh:
      hosts:
        agh1:
          ansible_host: 192.168.20.4
          ansible_user: james
          ansible_python_interpreter: /usr/bin/python3.12
          ansible_become: true
          ansible_become_method: sudo
        agh2:
          ansible_host: 192.168.20.5
          ansible_user: james
          ansible_python_interpreter: /usr/bin/python3.12
          ansible_become: true
          ansible_become_method: sudo
      vars:
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab
