---
- name: Sync AdGuard proxy into Nginx Proxy Manager
  hosts: unraid
  gather_facts: false
  vars:
    npm_proxy_config_paths:
      - "{{ playbook_dir }}/../../files/npm/services/certificates.yml"
      - "{{ playbook_dir }}/../../files/npm/services/adguard.yml"
    npm_manage_proxies: true
    npm_manage_dns: true
  roles:
    - npm
