#!/usr/bin/env python3
"""Generate a host-specific `ubuntu_env_container_vars` vault file from ~/.env_container."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys


def parse_env_container(path: pathlib.Path) -> dict[str, str]:
    data: dict[str, str] = {}
    export_re = re.compile(r"^export\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
    with path.open() as fp:
        for raw in fp:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            match = export_re.match(line)
            if not match:
                continue
            key = match.group(1)
            value = match.group(2)
            if (value.startswith('"') and value.endswith('"')) or (
                value.startswith("'") and value.endswith("'")
            ):
                value = value[1:-1]
            data[key] = value
    return data


def quote_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create ansible/host_vars/<host>.yml for ubuntu_env_container_vars."
    )
    parser.add_argument(
        "host",
        help="Inventory hostname (e.g., ubuntu-01); used to name the host_vars file.",
    )
    parser.add_argument(
        "--env",
        type=pathlib.Path,
        default=pathlib.Path.home() / ".env_container",
        help="Source .env_container file containing export statements.",
    )
    parser.add_argument(
        "--vault",
        action="store_true",
        help="Run `ansible-vault encrypt` on the generated file (prompts once).",
    )
    args = parser.parse_args()

    if not args.env.is_file():
        print(f"Source file {args.env} does not exist.", file=sys.stderr)
        return 1

    env_vars = parse_env_container(args.env)
    if not env_vars:
        print(f"No exportable vars found in {args.env}.", file=sys.stderr)
        return 1

    host_vars_dir = pathlib.Path("ansible") / "host_vars"
    host_vars_dir.mkdir(parents=True, exist_ok=True)
    target_file = host_vars_dir / f"{args.host}.yml"

    lines = ["# Generated by scripts/generate-ubuntu-env-vault.py", "ubuntu_env_container_vars:"]
    for key in sorted(env_vars):
        lines.append(f"  {key}: {quote_value(env_vars[key])}")

    target_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {target_file}.")

    if args.vault:
        result = subprocess.run(
            ["ansible-vault", "encrypt", str(target_file)],
            check=False,
        )
        if result.returncode != 0:
            print(
                "ansible-vault encrypt failed; remove the plaintext file if needed.",
                file=sys.stderr,
            )
        return result.returncode

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
